steps:
  - label: ":docker: Push to final repository"
    key: push
    plugins:
      - docker-login#v2.1.0:
          server: ghcr.io
          username: phanletrunghieu
          password-env: GITHUB_ACCESS_TOKEN
      - docker-compose#v3.9.0:
          push:
            - app:ghcr.io/ashswap/interface:${BUILDKITE_TAG}
          cache-from: app:ghcr.io/ashswap/interface:latest